db:
  log: true
  timeout: 5 # Query timeout in seconds
  createschema: false

server:
  port: ":8080"
  debug: true

jwt:
  realm: "jwtrealm" # Change this value
  secret: "jwtsecret" # Change this value
  duration: 15
  signingalgorithm: "HS256"